GreenSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('green.urls')),
    path('rooms/', include('rooms.urls')),
    path('shelves/', include('shelves.urls')),
    path('sensors/', include('sensors.urls')),
    path('relays/', include('relays.urls')),
    path('rules/', include('rules.urls')),
    path('admin/', admin.site.urls),
]

green/urls.py
from django.urls import path
from . import views

app_name = 'green'
urlpatterns = [
    # ex: /green/
    path('', views.index, name='index'),
    # path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('index/', views.index2, name='index2')
]

rules/urls.py
from django.urls import path
from . import views

app_name = 'rules'
urlpatterns = [
    path('', views.get_rules_list, name='get_rules_list'),
    path('add_new_rule/', views.add_new_rule, name='add_new_rule'),
    path('modify_the_rule/<int:rule_id>/', views.modify_the_rule, name='modify_the_rule'),
    path('delete_the_rule/<int:rule_id>/', views.delete_the_rule, name='delete_the_rule'),
    path('adapt_the_rule/<int:rule_id>/', views.adapt_the_rule, name='adapt_the_rule'),
]

rules/models.py
from django.db import models

# Create your models here.

rules/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404,HttpResponse
from django.urls import reverse, reverse_lazy
from green.models import Rules
from .utils import rules_set
import time
# Create your views here.


def get_rules_list(request):
    if request.user.is_authenticated:
        rules_list = Rules.objects.all()
        content = {
            'active_main_menu': '自动控制',
            'active_submenu': '规则列表',
            'rules_list': rules_list,
        }
        return render(request, "rules/rules_list.html", content)


def add_new_rule(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            content = {
                'active_main_menu': '自动控制',
                'active_submenu': '添加新规则',
            }
            return render(request, "rules/add_new_rule.html", content)
        if request.method == 'POST':
            name = request.POST.get('name')
            comment = request.POST.get('comment')
            status = request.POST.get('status')
            condition = request.POST.get('condition')
            performance = request.POST.get('performance')
            try:
                rule = Rules(name=name, comment=comment, status=status, condition=condition, performance=performance, created_time=int(time.time()))
                rule.save()
                rules_set()
            except Exception as e:
                print(e)
            return HttpResponseRedirect(reverse('rules:get_rules_list'))


def modify_the_rule(request, rule_id):
    if request.user.is_authenticated:
        if request.method == 'GET':
            rule = Rules.objects.get(id=rule_id)
            content = {
                'active_main_menu': '自动控制',
                'active_submenu': '修改规则',
                'rule': rule,
            }
            return render(request, 'rules/modify_the_rule.html', content)
        if request.method == 'POST':
            try:
                rule = Rules.objects.get(id=rule_id)
                rule.name = request.POST.get('name')
                rule.comment = request.POST.get('comment')
                rule.status = request.POST.get('status')
                rule.condition = request.POST.get('condition')
                rule.performance = request.POST.get('performance')
                rule.save()
                rules_set()
            except Exception as e:
                print(e)
            return HttpResponseRedirect(reverse('rules:get_rules_list'))


def delete_the_rule(request, rule_id):
    if request.user.is_authenticated:
        try:
            rule = Rules.objects.get(id=rule_id)
            rule.delete()
            rules_set()
        except Exception as e:
            print(e)
        return HttpResponseRedirect(reverse('rules:get_rules_list'))


def adapt_the_rule(request, rule_id):
    if request.user.is_authenticated:
        try:
            rule = Rules.objects.get(id=rule_id)
            if rule.status == -10:
                rule.status = 10
            elif rule.status == 10:
                rule.status = -10
            rule.save()
            rules_set()
        except Exception as e:
            print(e)
        return HttpResponseRedirect(reverse('rules:get_rules_list'))

rules/templates/rules/add_new_rule.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to IoT Lab.</span>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a7.jpg' %}">
                                </a>
                                <div class="media-body">
                                    <small class="float-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a4.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/profile.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="mailbox.html" class="dropdown-item">
                                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="mailbox.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="profile.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="float-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="grid_options.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html" class="dropdown-item">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>


                <li>
                    <a href="{% url 'green:logout' %}">
                        <i class="fa fa-sign-out"></i> 退出
                    </a>
                </li>
            </ul>

        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>{{ active_submenu }}</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'green:index' %}">主页</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a>{{ active_main_menu }}</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <strong>{{ active_submenu }}</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title">
                            <h5>{{ active_main_menu }} <small>{{ active_submenu }}</small></h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#" class="dropdown-item">Config option 1</a>
                                    </li>
                                    <li><a href="#" class="dropdown-item">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form method="post" class="m-t" role="form" action="{% url 'rules:add_new_rule' %}">
                                {% csrf_token %}
                                <div class="form-group  row"><label class="col-sm-2 col-form-label">规则名称</label>
                                    <div class="col-sm-10"><input type="text" class="form-control" required name="name"></div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row"><label class="col-sm-2 col-form-label">备注</label>
                                    <div class="col-sm-10"><input type="text" class="form-control" required name="comment"></div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row"><label class="col-sm-2 col-form-label">状态</label>

                                    <div class="col-sm-10"><select class="form-control m-b" required name="status">
                                        <option value="10">已启用</option>
                                        <option value="-10">已失效</option>
                                    </select>
                                    </div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row"><label class="col-sm-2 col-form-label">规则条件</label>
                                    <div class="col-sm-10"><textarea type="text" class="form-control" rows="20" required name="condition"></textarea></div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row"><label class="col-sm-2 col-form-label">规则执行</label>
                                    <div class="col-sm-10"><textarea type="text" class="form-control" rows="20" required name="performance"></textarea></div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row">
                                    <div class="col-sm-4 col-sm-offset-2">
                                        <button class="btn btn-white btn-sm" type="reset">重置</button>
                                        <button class="btn btn-primary btn-sm" type="submit">添加</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="pull-right">
                智能植物工厂管理系统
            </div>
            <div>
                <strong>Copyright</strong> 浙江大学城市学院 杭州市物联网技术与应用重点实验室 &copy; 2019
            </div>
        </div>

        </div>
{% endblock %}

{% block script %}

{% endblock %}

rules/templates/rules/rules_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to IoT Lab.</span>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a7.jpg' %}">
                                </a>
                                <div class="media-body">
                                    <small class="float-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a4.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/profile.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="mailbox.html" class="dropdown-item">
                                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="mailbox.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="profile.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="float-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="grid_options.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html" class="dropdown-item">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>


                <li>
                    <a href="{% url 'green:logout' %}">
                        <i class="fa fa-sign-out"></i> 退出
                    </a>
                </li>
            </ul>

        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>{{ active_submenu }}</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'green:index' %}">主页</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a>{{ active_main_menu }}</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <strong>{{ active_submenu }}</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>{{ active_submenu }}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#" class="dropdown-item">Config option 1</a>
                                </li>
                                <li><a href="#" class="dropdown-item">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover" style="width: 100%">
                    <thead>
                    <tr>
                        <th>规则名称</th>
                        <th>备注</th>
                        <th>状态</th>
                        <th>添加时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rule in rules_list %}
                    <tr>
                        <td>{{ rule.name }}</td>
                        <td>{{ rule.comment }}</td>
                        <td class="center">{% if rule.status == 10 %}
                            已启用
                            {% else %}
                            已失效
                        {% endif %}</td>
                        <td class="center">{{ rule.created_datetime }}</td>
                        <td class="center"><a style="color: #1ab394;" href="{% url 'rules:adapt_the_rule' rule.id %}">更改状态</a> | <a style="color: #1ab394;" href="{% url 'rules:modify_the_rule' rule.id %}">查看</a> | <a style="color: #1ab394;" href="{% url 'rules:modify_the_rule' rule.id %}">更新</a> | <a style="color: #1ab394;" href="{% url 'rules:delete_the_rule' rule.id %}">删除</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                        </div>

                    </div>
                </div>
            </div>
            </div>
        </div>
        <div class="footer">
            <div class="pull-right">
                智能植物工厂管理系统
            </div>
            <div>
                <strong>Copyright</strong> 浙江大学城市学院 杭州市物联网技术与应用重点实验室 &copy; 2019
            </div>
        </div>

        </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function(){
            $('#dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    {extend: 'copy'},
                    {extend: 'excel', title: '{{ active_submenu }}'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });
    </script>
{% endblock %}