GreenSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('green.urls')),
    path('rooms/', include('rooms.urls')),
    path('shelves/', include('shelves.urls')),
    path('sensors/', include('sensors.urls')),
    path('relays/', include('relays.urls')),
    path('rules/', include('rules.urls')),
    path('admin/', admin.site.urls),
]

green/urls.py
from django.urls import path
from . import views

app_name = 'green'
urlpatterns = [
    # ex: /green/
    path('', views.index, name='index'),
    # path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('index/', views.index2, name='index2')
]

rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'
urlpatterns = [
    path('', views.get_rooms_list, name='get_rooms_list'),
    path('add_new_room/', views.add_new_room, name='add_new_room'),
    path('modify_the_room/<int:room_id>/', views.modify_the_room, name='modify_the_room'),
    path('get_room_shelves/<int:room_id>/', views.get_room_shelves, name='get_room_shelves'),
    path('get_room_sensors/<int:room_id>/', views.get_room_sensors, name='get_room_sensors'),
    path('get_room_relays/<int:room_id>/', views.get_room_relays, name='get_room_relays'),
    path('room_environment/<int:room_id>/', views.room_environment, name='room_environment'),
]

rooms/models.py
from django.db import models
# Create your models here.

rooms/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect,Http404,HttpResponse
from django.contrib import auth
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from green.models import *
import datetime, time
# Create your views here.


def get_rooms_list(request):
    if request.user.is_authenticated:
        rooms_list = RoomInfo.objects.all()
        content = {
            'active_main_menu': '温室',
            'active_submenu': '温室列表',
            'rooms_list': rooms_list,
        }
        return render(request, "rooms/rooms_list.html", content)


def add_new_room(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            cities = QuanShi.objects.filter(parent=330000)
            content = {
                'active_main_menu': '温室',
                'active_submenu': '添加新温室',
                'cities': cities,
            }
            return render(request, "rooms/add_new_room.html", content)
        if request.method == 'POST':
            room_num = request.POST.get('room_num')
            room_name = request.POST.get('room_name')
            city = request.POST.get('city')
            area = request.POST.get('area')
            try:
                room = RoomInfo(room_num=room_num, room_name=room_name, city=city, area=area, status=0,
                                created_time=int(time.time()))
                room.save()
            except Exception as e:
                print(e)
            return HttpResponseRedirect(reverse('rooms:get_rooms_list'))


def modify_the_room(request, room_id):
    if request.user.is_authenticated:
        if request.method == 'GET':
            room = RoomInfo.objects.get(id=room_id)
            cities = QuanShi.objects.filter(parent=330000)
            content = {
                'active_main_menu': '温室',
                'active_submenu': '修改温室信息',
                'room': room,
                'cities': cities,
            }
            return render(request, "rooms/modify_the_room.html", content)
        if request.method == 'POST':
            try:
                room = RoomInfo.objects.get(id=room_id)
                room.room_num = request.POST.get('room_num')
                room.room_name = request.POST.get('room_name')
                room.city = request.POST.get('city')
                room.area = request.POST.get('area')
                room.save()
            except Exception as e:
                print(e)
            return HttpResponseRedirect(reverse('rooms:get_rooms_list'))


def get_room_shelves(request, room_id):
    if request.user.is_authenticated:
        shelves_list = FlowerShelf.objects.filter(room_id=room_id)
        content = {
            'active_main_menu': '花架',
            'active_submenu': '花架列表',
            'shelves_list': shelves_list,
        }
        return render(request, 'shelves/shelves_list.html', content)


def get_room_sensors(request, room_id):
    if request.user.is_authenticated:
        sensors_list = SensorInfo.objects.filter(belongto_type=2, belongto_id=room_id)
        sensor_type_list = SensorType.objects.all()
        rooms = RoomInfo.objects.all()
        shelves = FlowerShelf.objects.all()
        content = {
            'active_main_menu': '传感器',
            'active_submenu': '传感器列表',
            'sensors_list': sensors_list,
            'sensor_types': sensor_type_list,
            'rooms': rooms,
            'shelves': shelves,
        }
        return render(request, 'sensors/sensors_list.html', content)


def get_room_relays(request, room_id):
    if request.user.is_authenticated:
        relays_list = RelayInfo.objects.filter(belongto_type=2, belongto_id=room_id)
        rooms = RoomInfo.objects.all()
        shelves = FlowerShelf.objects.all()
        content = {
            'active_main_menu': '控制器',
            'active_submenu': '控制器列表',
            'relays_list': relays_list,
            'rooms': rooms,
            'shelves': shelves,
        }
        return render(request, 'relays/relays_list.html', content)


def room_environment(request, room_id):
    if request.user.is_authenticated:
        try:
            sensor_temperature = SensorInfo.objects.get(belongto_type=2, belongto_id=room_id, sensor_type_id=1)
            sensor_humidity = SensorInfo.objects.get(belongto_type=2, belongto_id=room_id, sensor_type_id=2)
            sensor_co2 = SensorInfo.objects.get(belongto_type=2, belongto_id=room_id, sensor_type_id=4)
            data_record_temperature = DataRecord.objects.filter(sensor_num=sensor_temperature.sensor_num).order_by(
                '-id')[:20]
            data_record_humidity = DataRecord.objects.filter(sensor_num=sensor_humidity.sensor_num).order_by('-id')[:20]
            data_record_co2 = DataRecord.objects.filter(sensor_num=sensor_co2.sensor_num).order_by('-id')[:20]
        except Exception as e:
            print(e)
        content = {
            'active_main_menu': '温室',
            'active_submenu': '温室环境',
            'data_record_temperature': data_record_temperature,
            'data_record_humidity': data_record_humidity,
            'data_record_co2': data_record_co2,
        }
        return render(request, 'rooms/room_environment.html', content)

rooms/templates/rooms/add_new_room.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to IoT Lab.</span>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a7.jpg' %}">
                                </a>
                                <div class="media-body">
                                    <small class="float-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a4.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/profile.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="mailbox.html" class="dropdown-item">
                                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="mailbox.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="profile.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="float-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="grid_options.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html" class="dropdown-item">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>


                <li>
                    <a href="{% url 'green:logout' %}">
                        <i class="fa fa-sign-out"></i> 退出
                    </a>
                </li>
            </ul>

        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>{{ active_submenu }}</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'green:index' %}">主页</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a>{{ active_main_menu }}</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <strong>{{ active_submenu }}</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title">
                            <h5>{{ active_main_menu }} <small>{{ active_submenu }}</small></h5>
                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#" class="dropdown-item">Config option 1</a>
                                    </li>
                                    <li><a href="#" class="dropdown-item">Config option 2</a>
                                    </li>
                                </ul>
                                <a class="close-link">
                                    <i class="fa fa-times"></i>
                                </a>
                            </div>
                        </div>
                        <div class="ibox-content">
                            <form method="post" class="m-t" role="form" action="{% url 'rooms:add_new_room' %}">
                                {% csrf_token %}
                                <div class="form-group  row"><label class="col-sm-2 col-form-label">温室编号</label>
                                    <div class="col-sm-10"><input type="text" class="form-control" required name="room_num"></div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row"><label class="col-sm-2 col-form-label">温室名字</label>
                                    <div class="col-sm-10"><input type="text" class="form-control" required name="room_name"></div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row"><label class="col-sm-2 col-form-label">城市</label>

                                    <div class="col-sm-10"><select class="form-control m-b" required name="city">
                                        <option value="">请选择</option>
                                        {% for city in cities %}
                                            <option>{{ city.name }}</option>
                                        {% endfor %}
                                    </select>
                                    </div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row"><label class="col-sm-2 col-form-label">地区</label>
                                    <div class="col-sm-10"><input type="text" class="form-control" required name="area"></div>
                                </div>

                                <div class="hr-line-dashed"></div>
                                <div class="form-group row">
                                    <div class="col-sm-4 col-sm-offset-2">
                                        <button class="btn btn-white btn-sm" type="reset">重置</button>
                                        <button class="btn btn-primary btn-sm" type="submit">添加</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="pull-right">
                智能植物工厂管理系统
            </div>
            <div>
                <strong>Copyright</strong> 浙江大学城市学院 杭州市物联网技术与应用重点实验室 &copy; 2019
            </div>
        </div>

        </div>
{% endblock %}

{% block script %}

{% endblock %}

rooms/templates/rooms/rooms_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" action="search_results.html">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                </div>
            </form>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to IoT Lab.</span>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a7.jpg' %}">
                                </a>
                                <div class="media-body">
                                    <small class="float-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/a4.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a class="dropdown-item float-left" href="profile.html">
                                    <img alt="image" class="rounded-circle" src="{% static 'img/profile.jpg' %}">
                                </a>
                                <div class="media-body ">
                                    <small class="float-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="mailbox.html" class="dropdown-item">
                                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="mailbox.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="profile.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="float-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <a href="grid_options.html" class="dropdown-item">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="float-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html" class="dropdown-item">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>


                <li>
                    <a href="{% url 'green:logout' %}">
                        <i class="fa fa-sign-out"></i> 退出
                    </a>
                </li>
            </ul>

        </nav>
        </div>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>{{ active_submenu }}</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'green:index' %}">主页</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a>{{ active_main_menu }}</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <strong>{{ active_submenu }}</strong>
                        </li>
                    </ol>
                </div>
                <div class="col-lg-2">

                </div>
            </div>
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>{{ active_submenu }}</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#" class="dropdown-item">Config option 1</a>
                                </li>
                                <li><a href="#" class="dropdown-item">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover" style="width: 100%">
                    <thead>
                    <tr>
                        <th>温室编号</th>
                        <th>温室名称</th>
                        <th>传感器数</th>
                        <th>执行器数</th>
                        <th>查看该温室下的</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for room in rooms_list %}
                    <tr>
                        <td>{{ room.room_num }}</td>
                        <td>{{ room.city }}{{ room.area }}-{{ room.room_name }}</td>
                        <td class="center">{{ room.sensors_count }}</td>
                        <td class="center">{{ room.relays_count }}</td>
                        <td class="center"><a style="color: #1ab394;" href="{% url 'rooms:modify_the_room' room.id %}">修改信息</a> | <a style="color: #1ab394;" href="{% url 'rooms:get_room_shelves' room.id %}">花架</a> | <a style="color: #1ab394;" href="{% url 'rooms:get_room_sensors' room.id %}">传感器</a> | <a style="color: #1ab394;" href="{% url 'rooms:get_room_relays' room.id %}">执行器</a> |  <a style="color: #1ab394" href="{% url 'rooms:room_environment' room.id %}">实时数据</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                        </div>

                    </div>
                </div>
            </div>
            </div>
        </div>
        <div class="footer">
            <div class="pull-right">
                智能植物工厂管理系统
            </div>
            <div>
                <strong>Copyright</strong> 浙江大学城市学院 杭州市物联网技术与应用重点实验室 &copy; 2019
            </div>
        </div>

        </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function(){
            $('#dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    {extend: 'copy'},
                    {extend: 'excel', title: '{{ active_submenu }}'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });
    </script>
{% endblock %}