GreenSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('green.urls')),
    path('rooms/', include('rooms.urls')),
    path('shelves/', include('shelves.urls')),
    path('sensors/', include('sensors.urls')),
    path('relays/', include('relays.urls')),
    path('rules/', include('rules.urls')),
    path('admin/', admin.site.urls),
]

green/urls.py
from django.urls import path
from . import views

app_name = 'green'
urlpatterns = [
    # ex: /green/
    path('', views.index, name='index'),
    # path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('index/', views.index2, name='index2')
]

relays/urls.py
from django.urls import path
from . import views

app_name = 'relays'

urlpatterns = [
    path('', views.get_relays_list, name='get_relays_list'),
    path('add_new_relay/', views.add_new_relay, name='add_new_relay'),
    path('modify_the_relay/<int:relay_id>/', views.modify_the_relay, name='modify_the_relay'),
    path('delete_the_relay/<int:relay_id>/', views.delete_the_relay, name='delete_the_relay'),
    path('adapt_the_relay/<int:relay_id>/', views.adapt_the_relay, name='adapt_the_relay'),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'
urlpatterns = [
    path('', views.get_rooms_list, name='get_rooms_list'),
    path('add_new_room/', views.add_new_room, name='add_new_room'),
    path('modify_the_room/<int:room_id>/', views.modify_the_room, name='modify_the_room'),
    path('get_room_shelves/<int:room_id>/', views.get_room_shelves, name='get_room_shelves'),
    path('get_room_sensors/<int:room_id>/', views.get_room_sensors, name='get_room_sensors'),
    path('get_room_relays/<int:room_id>/', views.get_room_relays, name='get_room_relays'),
    path('room_environment/<int:room_id>/', views.room_environment, name='room_environment'),
]

rules/urls.py
from django.urls import path
from . import views

app_name = 'rules'
urlpatterns = [
    path('', views.get_rules_list, name='get_rules_list'),
    path('add_new_rule/', views.add_new_rule, name='add_new_rule'),
    path('modify_the_rule/<int:rule_id>/', views.modify_the_rule, name='modify_the_rule'),
    path('delete_the_rule/<int:rule_id>/', views.delete_the_rule, name='delete_the_rule'),
    path('adapt_the_rule/<int:rule_id>/', views.adapt_the_rule, name='adapt_the_rule'),
]

sensors/urls.py
from django.urls import path
from . import views

app_name = 'sensors'

urlpatterns = [
    path('', views.get_sensors_list, name='get_sensors_list'),
    path('sensor_types/', views.sensor_types, name='sensor_types'),
    path('add_sensor_type/', views.add_sensor_type, name='add_sensor_type'),
    path('add_new_sensor/', views.add_new_sensor, name='add_new_sensor'),
    path('modify_the_sensor/<int:sensor_id>/', views.modify_the_sensor, name='modify_the_sensor'),
    path('delete_the_sensor/<int:sensor_id>/', views.delete_the_sensor, name='delete_the_sensor'),
    path('sensor_data/<int:sensor_id>/', views.sensor_data, name='sensor_data'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>智能植物工厂管理系统</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <!-- Toastr style -->
    <link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">

    <!-- Gritter -->
    <link href="{% static 'js/plugins/gritter/jquery.gritter.css' %}" rel="stylesheet">

    <link href="{% static 'DataTables/datatables.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/plugins/footable/footable.core.css' %}" rel="stylesheet">

    <!-- orris -->
    <link href="{% static 'css/plugins/morris/morris-0.4.3.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <img width="50px" height="50px" alt="image" class="rounded-circle circle-border" src="{% static 'img/a4.jpg' %}"/>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="block m-t-xs font-bold">{{ user.username }}</span>
                                <span class="text-muted text-xs block">Art Director <b class="caret"></b></span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="dropdown-item" href="{% url 'green:userinfo' %}">Profile</a></li>
                                <li><a class="dropdown-item" href="contacts.html">Contacts</a></li>
                                <li><a class="dropdown-item" href="mailbox.html">Mailbox</a></li>
                                <li class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'green:logout' %}">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IoT
                        </div>
                    </li>
                    <li id="温室">
                        <a href="#"><i class="fa fa-home"></i> <span class="nav-label">温室</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li id="温室列表"><a href="{% url 'rooms:get_rooms_list' %}">温室列表</a></li>
                            <li id="添加新温室"><a href="{% url 'rooms:add_new_room' %}">添加新温室</a></li>
                            <li id="新设备发现"><a href="dashboard_3.html">新设备发现</a></li>
                            <li id="温室最新概况"><a href="dashboard_4_1.html">温室最新概况</a></li>
                            <li id="全局温室预览"><a href="dashboard_5.html">全局温室预览</a></li>
                        </ul>
                    </li>
                    <li id="花架">
                        <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">花架</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li id="花架列表"><a href="{% url 'shelves:get_shelves_list' %}">花架列表</a></li>
                            <li id="添加新花架"><a href="{% url 'shelves:add_new_shelf' %}">添加新花架</a></li>
                        </ul>
                    </li>
                    <li id="传感器">
                        <a href="#"><i class="fa fa-magic"></i> <span class="nav-label">传感器</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li id="传感器列表"><a href="{% url 'sensors:get_sensors_list' %}">传感器列表</a></li>
                            <li id="添加新的传感器"><a href="{% url 'sensors:add_new_sensor' %}">添加新的传感器</a></li>
                            <li id="传感器类型"><a href="{% url 'sensors:sensor_types' %}">传感器类型</a></li>
                            <li id="添加新的传感器类型"><a href="{% url 'sensors:add_sensor_type' %}">添加新的传感器类型</a></li>
                        </ul>
                    </li>
                    <li id="控制器">
                        <a href="#"><i class="fa fa-laptop"></i> <span class="nav-label">控制器</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li id="控制器列表"><a href="{% url 'relays:get_relays_list' %}">控制器列表</a></li>
                            <li id="添加新的控制器"><a href="{% url 'relays:add_new_relay' %}">添加新的控制器</a></li>
                        </ul>
                    </li>
                    <li id="水肥设备">
                        <a href="index.html#"><i class="fa fa-tint"></i> <span class="nav-label">水肥设备</span>  <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li id="水肥设备列表"><a href="contacts.html">水肥设备列表</a></li>
                        </ul>
                    </li>
                    <li id="自动控制">
                        <a href="index.html#"><i class="fa fa-star"></i> <span class="nav-label">自动控制</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li id="规则列表"><a href="{% url 'rules:get_rules_list' %}">规则列表</a></li>
                            <li id="添加新规则"><a href="{% url 'rules:add_new_rule' %}">添加新规则</a></li>
                        </ul>
                    </li>
                    <li id="系统设置">
                        <a href="index.html#"><i class="fa fa-wrench"></i> <span class="nav-label">系统设置</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li id="个人信息"><a href="{% url 'green:userinfo' %}">个人信息</a></li>
                            <li id="退出"><a href="{% url 'green:logout' %}">退出</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
        </nav>
        {% block content %}{% endblock %}
    </div>

    <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <script src="{% static 'DataTables/pdfmake-0.1.36/pdfmake.min.js' %}"></script>
    <script src="{% static 'DataTables/pdfmake-0.1.36/vfs_fonts.js' %}"></script>
    <script src="{% static 'DataTables/datatables.min.js' %}" type="text/javascript" charset="UTF-8"></script>
    <script src="{% static 'js/plugins/dataTables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'js/plugins/footable/footable.all.min.js' %}"></script>

    <!-- Flot -->
    <script src="{% static 'js/plugins/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.tooltip.min.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.spline.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'js/plugins/flot/jquery.flot.pie.js' %}"></script>

    <!-- Peity -->
    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>
    <script src="{% static 'js/demo/peity-demo.js' %}"></script>

    <!-- Morris -->
    <script src="{% static 'js/plugins/morris/raphael-2.1.0.min.js' %}"></script>
    <script src="{% static 'js/plugins/morris/morris.js' %}"></script>

    <!-- Custom and plugin javascript -->
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
    <script src="{% static 'js/plugins/video/responsible-video.js' %}"></script>

    <!-- jQuery UI -->
    <script src="{% static 'js/plugins/jquery-ui/jquery-ui.min.js' %}"></script>

    <!-- GITTER -->
    <script src="{% static 'js/plugins/gritter/jquery.gritter.min.js' %}"></script>

    <!-- Sparkline -->
    <script src="{% static 'js/plugins/sparkline/jquery.sparkline.min.js' %}"></script>

    <!-- Sparkline demo data  -->
    <script src="{% static 'js/demo/sparkline-demo.js' %}"></script>

    <!-- ChartJS-->
    <script src="{% static 'js/plugins/chartJs/Chart.min.js' %}"></script>

    <!-- Toastr -->
    <script src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>
    <script src="{% static 'js/plugins/d3/d3.min.js' %}"></script>
    <script src="{% static 'js/plugins/c3/c3.min.js' %}"></script>

    <script src="{% static 'js/plugins/peity/jquery.peity.min.js' %}"></script>

    <script src="{% static 'js/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js' %}"></script>
    <script src="{% static 'js/plugins/jvectormap/jquery-jvectormap-cn-mill.js' %}"></script>

    <script>
        $(document).ready(function () {
           $('.navbar-minimalize').click();
        });
    </script>

    {% if active_submenu %}
    <script type="text/javascript">
        $('li#{{ active_main_menu }}').addClass("active");
        $('li#{{ active_submenu }}').addClass("active");
    </script>
    {% endif %}

    {% block script %} {% endblock %}
</body>
</html>